config/routes.rb
Rails.application.routes.draw do
  #devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'  }

  resources :sucursals
  resources :empleados

  post '/empresas/validar_rfc', to: 'empresas#validar_rfc', as: 'validar_rfc'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @sucursales = current_user.empresa.sucursals
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
    <section>
      <div class="container">
    
    <h3>
         Inicio
        <small></small>
    </h3>
    <%if @sucursales.empty?%>
      No hay sucursales
      <%= link_to new_sucursal_path do %>
                      <button class="btn btn-primary">
                        Agregar sucursal
                      </button>
                    <% end %>
    <%else%>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                Lista de Sucursales
              </div>
              <div class="panel-body">
                <div class="table-responsive">
                  <table class="table table-stripped table-hover">
                    <thead>
                      <tr>
                        <th> Nombre:</th>
                        <th>Numero de empleados:</th>
                        <th>Editar</th>
                        <th>Registrar empleado</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @sucursales.each do |sucursal| %>
                        <tr>
                         <td>
                            <%= link_to sucursal_path(sucursal) do %>
                              <%=sucursal.nombre%>
                            <%end%>
                         </td>
                         <td><%=link_to empleados_path(sucursal_id: sucursal.id) do%>
                            <%=sucursal.empleados.count%>
                          <%end%>
                         </td>
                          <td>
                            <%= link_to edit_sucursal_path(sucursal) do %>
                              <button class="btn btn-primary">
                                Editar
                              </button>
                            <% end %>
                          </td>
                          <td>
                          <%= link_to new_empleado_path do %>
                          <button class="btn btn-danger">
                            Agregar empleado
                          </button>
                        <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div> <!-- end of panel-body -->
              <div class="panel-footer clearfix">
                <div class="pull-right">
                    <%= link_to new_sucursal_path do %>
                      <button class="btn btn-primary">
                        Agregar sucursal
                      </button>
                    <% end %>
                </div>
              </div> <!-- end of panel-footer -->
          </div>
        </div>
      </div> <!-- end of col -->
    </div> <!-- end of row -->
    <%end%>
    </div>
</section>