config/routes.rb
Rails.application.routes.draw do
  #devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'  }

  resources :sucursals
  resources :empleados

  post '/empresas/validar_rfc', to: 'empresas#validar_rfc', as: 'validar_rfc'

end

app/models/empleado.rb
class Empleado < ApplicationRecord
  belongs_to :sucursal
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
    before_action :set_empleado, only: [:show, :edit, :update]

    def index
        @empleados = Empleado.all.where(sucursal_id: params[:sucursal_id])
    end
    def show
        
    end

    def edit

    end

    def update
    respond_to do |format|
        if @empleado.update(empleado_params)
            format.html { redirect_to root_path, notice: "empleado fue actualizado con éxito." }
            format.json { render :show, status: :ok, location: @empleado }
        else
            format.html { render :edit }
            format.json { render json: @empleado.errors, status: :unprocessable_entity }
        end
        end
    end

    def new
        @empleado = Empleado.new
    end

    def create
        @empleado = Empleado.new(empleado_params)
        respond_to do |format|
            if @empleado.save
                format.html { redirect_to @empleado, notice: 'empleado fue creado con éxito.' }
                format.json { render :show, status: :created, location: @empleado }
            else
                format.html { render :new }
                format.json { render json: @empleado.errors, status: :unprocessable_entity }
            end
        end
    end
    
    private
    def set_empleado
        @empleado = Empleado.find(params[:id])
    end
    def empleado_params
        params.require(:empleado).permit(:nombre, :rfc, :puesto, :sucursal_id)
    end

end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/views/empleados/_form.html.erb
 <%= form_with model: empleado, local: true do |f| %>
    <div class="form-group row">
        <%= f.label :sucursal_id, "Sucursal", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
        <%=f.select(:sucursal_id, current_user.empresa.sucursals.all.collect {|a| [a.nombre, a.id]}, {}, class: "form-control")%>
        </div>
    </div>
      
    <div class="form-group row">
        <%= f.label :nombre, 'Nombre', class:"col-sm-3 col-form-label" %>
         <div class="col-sm-9">
            <%= f.text_field :nombre,class: "form-control" %>
        </div>
    </div>

    
    <div class="form-group row">
            <%= f.label :rfc, class:"col-sm-3 col-form-label"  %>
            <div class="col-sm-9">
                <%if controller.action_name == "edit"%>
                    <%= f.text_field :rfc,class: "form-control", :readonly => true %>
                <%else%>
                    <%= f.text_field :rfc,class: "form-control" %>
                <%end%>
        </div>
    </div>

    <div class="form-group row">
            <%= f.label :puesto, class:"col-sm-3 col-form-label" %>
            <div class="col-sm-9">
                <%= f.text_field :puesto, class: "form-control" %>
        </div>
    </div>

    <%= f.submit class: "btn btn-primary" %>
 

  <% end %>

<script>
  new EmpleadosView();
</script>
  

app/views/empleados/edit.html.erb
<!-- Main section-->
<section>
    <!-- Page content-->
    <div class="container">
      <h3>
        Editar empleado
        <small></small>
      </h3>
      <% if @empleado.errors.any? %>
        <div class="row">
            <div class="col-lg-12">
                <div class="alert alert-danger">
                    <ul>
                        <% @empleado.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
      <% end %>

      <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Detalles de empleado
                </div>
                <div class="panel-body">
                    <div class="col-lg-6" style="background:#cbe1ef;">
                        <%= render 'form',empleado: @empleado %>
                    </div>
                    
                </div>
            </div>
        </div>
      </div>
    </div>
</section>

app/views/empleados/index.html.erb
    <section>
      <div class="container">
    
    <h3>
         Empleados de sucursal: <%=Sucursal.find(params[:sucursal_id]).nombre%>
        <small></small>
    </h3>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                Lista de empleados
              </div>
              <div class="panel-body">
                <div class="table-responsive">
                  <table class="table table-stripped table-hover">
                    <thead>
                      <tr>
                        <th>Nombre:</th>
                        <th>RFC:</th>
                        <th>Puesto</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @empleados.each do |empleado| %>
                        <tr>
                         <td>
                              <%=empleado.nombre%>
                            
                         </td>
                         <td><%=empleado.rfc%></td>
                         <td><%=empleado.puesto%></td>
                          <td>
                            <%= link_to edit_empleado_path(empleado) do %>
                              <button class="btn btn-primary">
                                Editar
                              </button>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div> <!-- end of panel-body -->
              <div class="panel-footer clearfix">
                <div class="pull-right">
                    <%= link_to root_path do %>
                      <button class="btn btn-primary">
                        Regresar
                      </button>
                    <% end %>
                </div>
              </div> <!-- end of panel-footer -->
          </div>
        </div>
      </div> <!-- end of col -->
    </div> <!-- end of row -->
    </div>
</section>

app/views/empleados/new.html.erb
<!-- Main section-->
<section>
  <!-- Page content-->
  <div class="container">
  <h3>
      Nuevo empleado
      <small></small>
  </h3>
  
      <% if @empleado.errors.any? %>
          <div class="row">
              <div class="col-lg-12">
              <div class="alert alert-danger">
                  <strong>
                      <%= pluralize(@empleado.errors.count, "error") %> 
                  </strong>
                  <ul>
                      <% @empleado.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                      <% end %>
                  </ul>
              </div>
          </div>
          </div>
      <% end %>
  
  <div class="row">
      <div class="col-lg-12">
          <div class="panel panel-default">
              
              <div class="panel-body">

                  <div class="row">
                      <%= render 'form', empleado: @empleado %>
                  </div>
              </div>
          </div>
      </div>
  </div>
  </div>
</section>

app/views/empleados/show.html.erb
<section>
    <!-- Page content-->
    <div class="container">
    <h3>
         Empleado
        <small></small>
    </h3>
    
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
            <div class="panel-heading">
                  Detalles de empleado
                </div>
              <div class="panel-body">
                <table class="table bb">
                <tr>
                <p>
                    <td><strong>Sucursal:</strong></td>
                    <td><%=@empleado.sucursal.nombre%></td>
                </p>
                </tr>
                <tr>
                <p>
                    <td><strong>Nombre:</strong></td>
                    <td><%=@empleado.nombre%></td>
                </p>
                </tr>
                <tr>
                    <p>
                        <td><strong>RFC:</strong></td>
                        <td><%=@empleado.rfc%></td>
                    </p>
                </tr>
                <tr>
                    <p>
                        <td><strong>Puesto:</strong></td>
                        <td><%=@empleado.puesto%></td>
                    </p>
                </tr>
                

                </table>
                <div class="panel-footer clearfix">
                  <div class="pull-right">
                    <%= link_to root_path do %>
                      <button class="btn btn-primary"> Regresar </button>
                    <% end %>
                  </div>
                </div>
                
              </div>
            </div>
        </div>
    </div>

    </div>
</section>